apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dino-game
  template:
    metadata:
      labels:
        app: dino-game
    spec:
      containers:
      - name: dino-game
        image: your-dockerhub-username/dino-game
        ports:
        - containerPort: 8081
